### ISSUE TITLE
Command strings have docker containers running in Interative mode

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/gamesvr-tf2classic-freeplay#2]
I was just looking at the readme.md file as reference, I just noticed that all the strings for launching the server for TF2 classic. All the strings have the docker container launch in interactive mode. 

docker **run -it** --rm --net=host lacledeslan/gamesvr-tf2classic-freeplay ./srcds_run -game tf2classic +map vip_harbor +maxplayers 32 +mapcycle "mapcycle_quickplay_vip.txt"

Is this intentional?

**Comment by dudleycodes** [comment]
Yes - the readme is geared towards newcomers.  All the other example snippets in readmes should use `-it` not `-d`.
